### ISSUE TITLE
teeks99-08-f-win2016-64on64: Boost.System shared library problem

### ISSUE THREAD

**Issue by Kojoley** [teeks99/boost-build#1]
I am not sure what exactly happens on [`teeks99-08-f-win2016-64on64` runner](https://www.boost.org/development/tests/develop/developer/output/teeks99-08-f-win2016-64on64-boost-bin-v2-libs-system-test-after_main_test_shared-test-msvc-14-0-dbg-adrs-mdl-64-thrd-mlt.html), every target that does `<library>/boost/system//boost_system` or `/boost//system` fails. I cannot reproduce this locally and other msvc-14.0 runner teeks99-09-f-win2012R2-64on64 is fine. Usually that happens when there is no symbols to export and MSVC silently do not produce a shared library, but it says that `boost_system-vc140-mt-gd-x64-1_70.lib` library is created and Boost.System exports a dummy function to prevent this.

cc @pdimov

**Comment by Kojoley** [comment]
It seems that the runner have problems with finding linker https://www.boost.org/development/tests/develop/developer/output/teeks99-08-f-win2016-64on64-boost-bin-v2-boost-build-tests-msvc-14-0-absolute_sources.html

And it reminds https://groups.google.com/forum/#!topic/boost-developers-archive/Xr9qz6ZTpJ8 / http://boost.2283326.n4.nabble.com/release-build-Errors-compiling-1-68-0-with-VS2015-after-VS2017-td4704080.html

**Comment by pdimov** [comment]
`mt.exe` is the manifest tool. This happens on machines that have the 2015 toolset installed as part of VS2017, but don't have VS2015 installed.

**Comment by Kojoley** [comment]
I do not when it started, but I get the same problem for msvc-9, and `embed-manifest=off` workarounds it.

**Comment by Kojoley** [comment]
IIUC the worker was renamed to `teeks99-09-f-64onAMD64` and since https://github.com/boostorg/build/pull/604 the error message `LINK : fatal error LNK1158: cannot run 'rc.exe'` clearly indicates that either VS finds either malfunction WinSDK or none at all.

**Comment by teeks99** [comment]
I've updated that runner so that it's Visual Studio 2017 (not 2015!) includes the `Windows 10 SDK (10.0.10586.0)` package and that seems to have solved a lot of problems with that runner.

**Comment by Kojoley** [comment]
Thanks, Tom!
